DATASET:
  NAME: ILSVRC2012
  NUM_CLASSES: 1000
  NUM_WORKERS: 8
SOLVER:
  BASE_LR: 0.0075
  WEIGHT_DECAY: 1e-4
  TRAIN_BATCH_SIZE: 96
  WARMUP: True
  WARMUP_EPOCH: 5
  WARMUP_FACTOR: 0.2
ISON:
  TRANS_FUN: 'bottleneck_transform'
  DEPTH: 50
  ORTHO_COEFF: 1e-4
  HAS_BN: False
  HAS_ST: False
  SReLU: True
  DIRAC_INIT: True
  DROPOUT: True
  DROPOUT_RATE: 0.1
